[package]
edition = "2021"
license = "AGPL-3.0"
name = "bloom"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
bitvec.workspace = true
serde.workspace = true
xxhash-rust = "0.8.10"
