cluster_id = "dev_api"
# crossencoder_model_path = "data/cross_encoder"
gossip_addr = "0.0.0.0:3005"
gossip_seed_nodes = ["0.0.0.0:3006", "0.0.0.0:3007"]
host = "0.0.0.0:3000"
management_host = "0.0.0.0:3011"
# lambda_model_path = "data/lambdamart.txt"
bangs_path = "data/bangs.json"
# dual_encoder_model_path = "data/dual_encoder"
prometheus_host = "0.0.0.0:3001"
top_phrases_for_autosuggest = 1_000

[spell_check]
path = "data/web_spell/checker"

[spell_check.correction_config]
correction_threshold = 0.0
lm_prob_weight = 1.0

[thresholds]
entity_sidebar = 0.0
stackoverflow = 0.0

[widgets]
thesaurus_paths = ["data/english-wordnet-2022-subset.ttl"]
